using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace MultiplayerEvents
{
    /// taken from https://github.com/Kerr1291/EnemyRandomizer/blob/master/EnemyRandomizerDll/EnemyRandomizer/EnemyRandomizerDatabase.cs and modified slightly
    internal class EnemyDatabase
    {
        public static List<string> flyerEnemyTypeNames = new List<string>()
        {
            "Mosquito",
            "Blobble",
            "Giant Buzzer Col",
            "Buzzer Col",
            "Super Spitter Col",
            "Mega Fat Bee",
            "Mage",
            "Giant Fly Col",
            "Mage Balloon",
            "Electric Mage",
            "Angry Buzzer",
            "Spitter",
            "Buzzer",
            "Fly",
            "Bursting Bouncer",
            "Hatcher",
            "Ruins Flying Sentry",
            "Ruins Flying SentryB",
            "Ruins Flying Sentry Javelin",
            "Mage Lord Phase2",
            "Mage Lord",
            "Acid Flyer",
            "Fat Fly",
            "Giant Buzzer",
            "Lazy Flyer Enemy",
            "Ghost Warrior No Eyes",
            "Fungus Flyer",
            "Fungoon Baby",
            "Ghost Warrior Hu",
            "Jellyfish Baby",
            "Jellyfish",
            "Mantis Heavy Flyer",
            "Moss Flyer",
            "Ghost Warrior Marmu",
            "Mega Jellyfish",
            "Ghost Warrior Slug",
            "Ghost Warrior Xero",
            "Centipede Hatcher",
            "Spider Flyer",
            "Ghost Warrior Galien",
            "Blow Fly",
            "Bee Hatchling Ambient",
            "Super Spitter",
            "Ghost Warrior Markoth",
            "Shade Sibling",
            "Parasite Balloon",
            "Inflater",
            "Fluke Fly",
            "Fluke Mother",
            "White Palace Fly",
            "Bee Stinger",
            "Big Bee",
            "Mosquito",
            "Zote Balloon",
            "Zoteling",
            "Dream Mage Lord",
            "Dream Mage Lord Phase2",
            "Colosseum_Flying_Sentry",
            "Colosseum_Armoured_Mosquito",
            "Radiance"
        };

        public static List<string> groundEnemyTypeNames = new List<string>()
        {
            "Colosseum_Miner",
            "Colosseum_Armoured_Roller",
            "Colosseum_Shield_Zombie",
            "Colosseum_Worm",
            "Giant Fly",
            "Lancer",
            "Lobster",
            "Mage Blob",
            "Mage Knight",
            "Zombie Runner",
            "Bursting Zombie",
            "Mender Bug",
            "Crawler",
            "Zombie Hornhead",
            "Zombie Barger",
            "Spitting Zombie",
            "Mawlek Body",
            "Prayer Slug",
            "Blocker",
            "Zombie Shield",
            "Zombie Leaper",
            "Zombie Guard",
            "Zombie Myla",
            "Roller",
            "Great Shield Zombie",
            "Royal Zombie Coward",
            "Royal Zombie",
            "Gorgeous Husk",
            "Royal Zombie Fat",
            "Ruins Sentry",
            "Ruins Sentry FatB",
            "Ruins SentryB",
            "Ruins Sentry Fat B",
            "Ruins Sentry Fat",
            "Great Shield Zombie bottom",
            "Black Knight",
            "Jar Collector",
            "Pigeon",
            "Mossman_Runner",
            "Moss Walker",
            "Mossman_Shaker",
            "Hornet Boss",
            "Moss Charger",
            "Shell",
            "Moss Knight",
            "Grass Hopper",
            "Mega Moss Charger",
            "Moss Knight C",
            "Moss Knight B",
            "Zombie Fungus",
            "Fung Crawler",
            "Mushroom Baby",
            "Mushroom Brawler",
            "Mushroom Roller",
            "Zombie Fungus A",
            "Mantis",
            "Mantis Flyer Child",
            "Jellyfish Baby",
            "Mantis Heavy",
            "Garden Zombie",
            "Mantis Traitor Lord",
            "Moss Knight Fat",
            "Mantis Heavy Spawn",
            "Grave Zombie",
            "Zombie Miner",
            "Crystal Crawler",
            "Crystal Flyer",
            "Grub Mimic",
            "Mega Zombie Beam Miner",
            "Zombie Beam Miner",
            "Zombie Beam Miner Rematch",
            "Baby Centipede",
            "Zombie Runner Sp",
            "Zombie Spider 1",
            "Zombie Hornhead Sp",
            "Zombie Spider 2",
            "Mimic Spider",
            "Slash Spider",
            "Tiny Spider",
            "Giant Hopper",
            "Hopper",
            "Abyss Crawler",
            "Lesser Mawlek",
            "Infected Knight",
            "Flip Hopper",
            "Flukeman",
            "Dung Defender",
            "Royal Gaurd",
            "Enemy",
            "Zombie Hive",
            "Hive Knight",
            "Grimm Boss",
            "Nightmare Grimm Boss",
            "False Knight Dream",
            "Lost Kin",
            "White Defender",
            "Grey Prince",
            "Hollow Knight Boss"
        };

        public static List<string> smallEnemyTypeNames = new List<string>()
        {
            "Mosquito",
            "Buzzer Col",
            "Blobble",
            "Colosseum_Armoured_Roller",
            "Colosseum_Armoured_Mosquito",
            "Colosseum_Flying_Sentry",
            "Colosseum_Shield_Zombie",
            "Super Spitter Col",
            "Colosseum_Worm",
            "Colosseum_Miner",
            "Mega Fat Bee",
            "Mage Knight",
            "Mage Blob",
            "Mage Balloon",
            "Zombie Runner",
            "Giant Fly Col",
            "Angry Buzzer",
            "Bursting Zombie",
            "Mender Bug",
            "Climber",
            "Spitter",
            "Buzzer",
            "Zombie Hornhead",
            "Fly",
            "Zombie Barger",
            "Spitting Zombie",
            "Climber",
            "Bursting Bouncer",
            "Prayer Slug",
            "Zombie Shield",
            "Mawlek Body",
            "Angry Buzzer",
            "Hatcher",
            "Zombie Leaper",
            "Zombie Myla",
            "Roller",
            "Great Shield Zombie",
            "Royal Zombie Coward",
            "Royal Zombie",
            "Gorgeous Husk",
            "Royal Zombie Fat",
            "Ruins Sentry",
            "Ceiling Dropper",
            "Ceiling Dropper Col",
            "Ruins Flying Sentry",
            "Ruins Sentry FatB",
            "Ruins SentryB",
            "Ruins Flying SentryB",
            "Ruins Sentry Fat B",
            "Ruins Flying Sentry Javelin",
            "Ruins Sentry Fat",
            "Black Knight",
            "Ceiling Dropper", //
            "Plant Trap", //
            "Plant Turret", //
            "Laser Turret Frames", //
            "Mawlek Turret Ceiling", //
            "Mawlek Turret", //
            "Worm", //
            "Mushroom Turret",
            "Mines Crawler", //
            "Abyss Crawler", //
            "Climber", //
            "Crystallised Lazer Bug",
            "Spider Mini",
            "Jar Collector",
            "Pigeon",
            "Mossman_Runner",
            "Moss Walker",
            "Mossman_Shaker",
            "Hornet Boss",
            "Acid Flyer",
            "Plant Turret Right",
            "Fat Fly",
            "Giant Buzzer",
            "Grass Hopper",
            "Lazy Flyer Enemy",
            "Fungus Flyer",
            "Fungoon Baby",
            "Zombie Fungus",
            "Fung Crawler",
            "Mushroom Baby",
            "Mushroom Brawler",
            "Mushroom Roller",
            "Zombie Fungus A",
            "Mantis",
            "Jellyfish",
            "Mantis Heavy Flyer",
            "Moss Flyer",
            "Mantis Heavy",
            "Garden Zombie",
            "Mantis Traitor Lord",
            "Moss Knight Fat",
            "Mantis Heavy Spawn",
            "Grave Zombie",
            "Zombie Miner",
            "Crystal Crawler",
            "Crystal Flyer",
            "Grub Mimic",
            "Mega Zombie Beam Miner",
            "Zombie Beam Miner",
            "Zombie Beam Miner Rematch",
            "Baby Centipede",
            "Zombie Runner Sp",
            "Zombie Spider 1",
            "Zombie Hornhead Sp",
            "Zombie Spider 2",
            "Slash Spider",
            "Tiny Spider",
            "Spider Flyer",
            "Bee Hatchling Ambient",
            "Super Spitter",
            "Giant Hopper",
            "Hopper",
            "Shade Sibling",
            "Lesser Mawlek",
            "Parasite Balloon",
            "Flip Hopper",
            "Inflater",
            "Flukeman",
            "Fluke Fly",
            "White Palace Fly",
            "Royal Gaurd",
            "Enemy",
            "Giant Buzzer Col",
            "Zombie Hive",
            "Bee Stinger",
            "Big Bee",
            "Zote Balloon",
            "Zoteling",
            "Crawler"
        };

        public static List<string> mediumEnemyTypeNames = new List<string>()
        {
            "Mosquito",
            "Colosseum_Worm",
            "Colosseum_Flying_Sentry",
            "Colosseum_Miner",
            "Colosseum_Shield_Zombie",
            "Mega Fat Bee",
            "Mage Knight",
            "Mage",
            "Electric Mage",
            "Angry Buzzer",
            "Blocker",
            "Mawlek Body",
            "Great Shield Zombie",
            "Gorgeous Husk",
            "Giant Fly Col",
            "Royal Zombie Fat",
            "Ruins Sentry",
            "Ruins Flying Sentry",
            "Ruins Sentry FatB",
            "Ruins SentryB",
            "Ruins Flying SentryB",
            "Ruins Sentry Fat B",
            "Ruins Flying Sentry Javelin",
            "Ruins Sentry Fat",
            "Black Knight",
            "Jar Collector",
            "Hornet Boss",
            "Shell",
            "Fat Fly",
            "Giant Buzzer",
            "Lazy Flyer Enemy",
            "Fungus Flyer",
            "Mushroom Brawler",
            "Mushroom Roller",
            "Mantis",
            "Mantis Flyer Child",
            "Jellyfish",
            "Mantis Heavy Flyer",
            "Mantis Heavy",
            "Mantis Traitor Lord",
            "Moss Knight Fat",
            "Mantis Heavy Spawn",
            "Grave Zombie",
            "Crystal Crawler",
            "Grub Mimic",
            "Mega Zombie Beam Miner",
            "Zombie Beam Miner",
            "Zombie Beam Miner Rematch",
            "Centipede Hatcher",
            "Slash Spider",
            "Spider Flyer",
            "Giant Hopper",
            "Shade Sibling",
            "Lesser Mawlek",
            "Flip Hopper",
            "Inflater",
            "Flukeman",
            "Royal Gaurd",
            "Zombie Hive",
            "Bee Stinger",
            "Big Bee"
        };

        public static List<string> bigEnemyTypeNames = new List<string>()
        {
            "Mosquito",
            "Colosseum_Worm",
            "Giant Buzzer Col",
            "Mega Fat Bee",
            "Lancer",
            "Lobster",
            "Mage Knight",
            "Giant Fly",
            "Mawlek Body",
            "Zombie Guard",
            "Great Shield Zombie",
            "Gorgeous Husk",
            "Mage Lord Phase2",
            "Mage Lord",
            "Great Shield Zombie bottom",
            "Black Knight",
            "Jar Collector",
            "Moss Charger",
            "Fat Fly",
            "Giant Buzzer",
            "Moss Knight",
            "Lazy Flyer Enemy",
            "Mega Moss Charger",
            "Moss Knight C",
            "Giant Fly Col",
            "Moss Knight B",
            "Ghost Warrior No Eyes",
            "Fungus Flyer",
            "Mushroom Brawler",
            "Ghost Warrior Hu",
            "Jellyfish",
            "Mantis Traitor Lord",
            "Moss Knight Fat",
            "Ghost Warrior Marmu",
            "Mega Jellyfish",
            "Ghost Warrior Slug",
            "Ghost Warrior Xero",
            "Grave Zombie",
            "Centipede Hatcher",
            "Mimic Spider",
            "Ghost Warrior Galien",
            "Blow Fly",
            "Giant Hopper",
            "Ghost Warrior Markoth",
            "Shade Sibling",
            "Infected Knight",
            "Inflater",
            "Dung Defender",
            "Fluke Mother",
            "Royal Gaurd",
            "Zombie Hive",
            "Bee Stinger",
            "Big Bee",
            "Hive Knight",
            "Grimm Boss",
            "Nightmare Grimm Boss",
            "False Knight Dream",
            "Dream Mage Lord",
            "Dream Mage Lord Phase2",
            "Lost Kin",
            "White Defender",
            "Grey Prince",
            "Radiance",
            "Hollow Knight Boss"
        };

        public static List<string> wallEnemyTypeNames = new List<string>()
        {
            "Ceiling Dropper Col",//34
            "Ceiling Dropper", //??(forgot)
            "Plant Trap", //117
            "Plant Turret", //127
            "Laser Turret Frames", //234
            "Mawlek Turret Ceiling", //321
            "Mawlek Turret", //321
            "Worm", //49
            "Mushroom Turret",
            "Plant Turret Right",
            "Mushroom Turret"
        };

        public static List<string> crawlerEnemyTypeNames = new List<string>()
        {
            "Mines Crawler", //243
            "Abyss Crawler", //320
            "Climber", //40
            "Crystallised Lazer Bug", //243 (this was removed from the list for some reason???)
            "Spider Mini" //271
        };

        public static List<string> colloseumEnemyTypes = new List<string>()
        {
            "Mosquito",
            "Giant Buzzer Col",
            "Colosseum_Miner",
            "Mega Fat Bee",
            "Lancer",
            "Lobster",
            "Mage",
            "Mage Balloon",
            "Electric Mage",

            "Mage Blob",
            "Mage Knight",
            "Giant Hopper",


            "Colosseum_Armoured_Roller",
            "Super Spitter Col",
            "Colosseum_Worm",
            "Ceiling Dropper Col",
            "Super Spitter",
            "Mantis Heavy Flier",
            "Mantis Heavy",
            "Colosseum Grass Hopper",
            "Mawlek Col",
            "Buzzer Col",
            "Lesser Mawlek",
            "Angry Buzzer",
            "Mage Knight",
            "Mage Blob",
            "Giant Fly Col",
            "Blobble",
            "Hopper",
            "Colosseum_Flying_Sentry",
            "Colosseum_Armoured_Mosquito",
            "Colosseum_Shield_Zombie",
            "Grub Mimic",
            "Blobble",
            "Bursting Bouncer",


            "Dung Defender"
        };

        public static List<string> hardEnemyTypeNames = new List<string>()
        {
            "Mage Knight",
            "Electric Mage",
            "Giant Buzzer Col",
            "Mega Fat Bee",
            "Giant Buzzer",
            "Lancer",
            "Lobster",
            "Mawlek Body",
            "Great Shield Zombie",
            "Gorgeous Husk",
            "Mage Lord Phase2",
            "Mage Lord",
            "Great Shield Zombie bottom",
            "Jar Collector",
            "Hornet Boss",
            "Moss Knight",
            "Mega Moss Charger",
            "Giant Fly Col",
            "Moss Knight C",
            "Moss Knight B",
            "Ghost Warrior No Eyes",
            "Mushroom Brawler",
            "Ghost Warrior Hu",
            "Big Bee",
            "Mantis Traitor Lord",
            "Moss Knight Fat",
            "Ghost Warrior Marmu",
            "Mega Jellyfish",
            "Ghost Warrior Slug",
            "Ghost Warrior Xero",
            "Mega Zombie Beam Miner",
            "Zombie Beam Miner Rematch",
            "Centipede Hatcher",
            "Mimic Spider",
            "Ghost Warrior Galien",
            "Ghost Warrior Markoth",
            "Infected Knight",
            "Fluke Mother",
            "Royal Gaurd",
            "Hive Knight",
            "Grimm Boss",
            "Nightmare Grimm Boss",
            "False Knight Dream",
            "Dream Mage Lord",
            "Dream Mage Lord Phase2",
            "Lost Kin",
            "White Defender",
            "Grey Prince",
            "Radiance",
            "Hollow Knight Boss",
            "Centipede Hatcher",
            "Electric Mage",//35
            "Mage Knight",//35
            "Giant Buzzer Col",//33
            "Giant Fly Col",//34 
            "Lancer",//35
            "Lobster",//35
            "Mawlek Body", //46 (mini boss)
            "Moss Knight", //137            
            "Mushroom Brawler", //
            "Royal Gaurd", //358
            "Mimic Spider", //269 (Nosk, BOSS)
            "Zombie Beam Miner Rematch", //241
            "Mantis Traitor Lord" //194
        };
    }
}
